-- MySQL Script generated by MySQL Workbench
-- jue 28 feb 2019 20:06:51 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbVBA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbVBA` ;

-- -----------------------------------------------------
-- Schema dbVBA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbVBA` DEFAULT CHARACTER SET utf8 ;
USE `dbVBA` ;

-- -----------------------------------------------------
-- Table `dbVBA`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbVBA`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `dbVBA`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nUsuario` VARCHAR(45) NOT NULL,
  `nPass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
